using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
// A reference needs to be added for AutoLotDAL3 for the following to work
using AutoLotDAL3;
using static AutoLotDAL3.DataSets.AutoLotDataSet;
using AutoLotDAL3.DataSets.AutoLotDataSetTableAdapters;
using AutoLotDAL3.DataSets;

namespace StronglyTypedDataSetWindowsFormsDesigner
{
    /// <summary>
    /// Simple program to demonstrate use of forms designer and dataset designer without 
    /// using a cumbersome wizard for multiple tables
    /// </summary>
    public partial class StronglyTypedDataSetWindowsFormsDesignerMainForm : Form
    {
        // create DataTables and Adapters

        AutoLotDataSet autoLotDataSet = new AutoLotDataSet();

        InventoryDataTable inventoryTable = new InventoryDataTable();
        InventoryTableAdapter inventoryTableAdapter = new InventoryTableAdapter();

        CustomersDataTable customersTable = new CustomersDataTable();
        CustomersTableAdapter customersTableAdapter = new CustomersTableAdapter();

        OrdersDataTable ordersTable = new OrdersDataTable();
        OrdersTableAdapter ordersTableAdapter = new OrdersTableAdapter();

        public StronglyTypedDataSetWindowsFormsDesignerMainForm()
        {
            InitializeComponent();

            // fill the datatables from the database

            inventoryTableAdapter.Fill(inventoryTable);
            customersTableAdapter.Fill(customersTable);
            ordersTableAdapter.Fill(ordersTable);

            // initialize the controls

            InitializeDataGridView(dataGridViewInventory, inventoryTable);
            InitializeDataGridView(dataGridViewCustomers, customersTable);
            InitializeDataGridView(dataGridViewOrders, ordersTable);

            // set the button event handler

            buttonUpdate.Click += ButtonUpdate_Click;
        }
        /// <summary>
        /// Update the database using table adapters update and fill methods
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void ButtonUpdate_Click(object sender, EventArgs e)
        {
            inventoryTableAdapter.Update(inventoryTable);
            customersTableAdapter.Update(customersTable);
            ordersTableAdapter.Update(ordersTable);

            inventoryTableAdapter.Fill(inventoryTable);
            customersTableAdapter.Fill(customersTable);
            ordersTableAdapter.Fill(ordersTable);
        }

        /// <summary>
        /// Basic gridview properties set here.
        /// Set the datasource, and make sure columns are autogenerated
        /// </summary>
        /// <param name="gridView"></param>
        /// <param name="table"></param>
        private void InitializeDataGridView(DataGridView gridView, DataTable table)
        {
            gridView.AutoGenerateColumns = true;
            gridView.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            gridView.DataSource = table;
        }
    }

 
}
